change feature Id constructor (adding nullfeatureId) + small changes
vpenades/SharpGLTF pull request #213
Opened 2024-01-04 20:14 UTC by bertt

2024-01-04 20:46 UTC, bertt commented on src/SharpGLTF.Ext.3DTiles/Schema2/Ext.Features.cs
> -                if (texture != null)
must be added somewhere else?

2024-01-04 21:09 UTC, bertt commented on src/SharpGLTF.Ext.3DTiles/Schema2/Ext.Features.cs
> -                if (texture != null)
added again https://github.com/vpenades/SharpGLTF/pull/213/commits/93f3d5178e053d5962954ab99f5cc46d26085386

2024-01-11 15:14 UTC, bertt commented on src/SharpGLTF.Ext.3DTiles/Schema2/Ext.StructuralMetadataRoot.cs
> +            public StructuralMetadataSchema UseExternalSchema(Uri uri)
here the method for setting external schema uri, it works but doesn't use a ISchemaProxy

2024-01-11 21:04 UTC, vpenades requested changes
Other that that, everything else looks fine.

2024-01-11 21:04 UTC, vpenades commented on src/SharpGLTF.Core/Schema2/_Extensions.Nullables.cs
> -using System.Text;
Although these changes are fine, they're not relevant to this PR.

2024-01-14 20:34 UTC, bertt commented on src/SharpGLTF.Ext.3DTiles/Schema2/Ext.StructuralMetadataRoot.cs
> +            public StructuralMetadataSchema UseExternalSchema(Uri uri)
external schema is not supported for now

2024-01-24 13:31 UTC, merged